-- AlterTable
ALTER TABLE "CollectedBook" ALTER COLUMN "book_name" DROP NOT NULL,
ALTER COLUMN "author_name" DROP NOT NULL,
ALTER COLUMN "hyperlink" DROP NOT NULL,
ALTER COLUMN "price" DROP NOT NULL,
ALTER COLUMN "seller" DROP NOT NULL,
ALTER COLUMN "found_time" DROP NOT NULL,
ALTER COLUMN "found_time" DROP DEFAULT;
